title: Natural Language Processing with Python
author: Tyler Shoemaker and Carl Stahmer
copyright: "2022"
logo: img/datalab-logo-full-color-rgb.png
only_build_toc_files: true

repository:
  url: https://github.com/ucdavisdatalab/workshop_nlp_with_python

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - html_image
    - linkify
    - substitution

execute:
  execute_notebooks: force
  timeout: 360

html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">
      <img alt="CC BY-SA 4.0" src="https://img.shields.io/badge/License-CC%20BY--NC--SA%204.0-lightgrey.svg"> 
    </a>

sphinx:
  config:
    html_show_copyright: false
