title: Natural Language Processing with Python
author: Tyler Shoemaker and Carl Stahmer
copyright: "2022"
logo: img/datalab-logo-full-color-rgb.png
only_build_toc_files: true

repository:
  url: https://github.com/ucdavisdatalab/workshop_nlp_with_python

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - html_image
    - linkify
    - substitution

execute:
  execute_notebooks: force
  timeout: 120

html:
  use_repository_button: true

